[package]
name = "lambda-calculus"
version = "0.1.0"
authors = ["Nathan Stoddard <nstoddard@users.noreply.github.com>"]
edition = "2018"
description = "A lambda calculus interpreter that works on desktop and wasm"

[lib]
crate-type = ["cdylib"]
name = "lambda_calculus_wasm"

[dependencies]
nom = "5.1.2"
anyhow = "1.0.33"
simple-error = "0.2.2"
hashbag = "0.1.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rustyline = "6.3.0"
directories-next = "1.0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.68"
console_error_panic_hook = "0.1.6"
yew = "0.17.4"
web-sys = { version = "0.3.45", features = [
  "HtmlElement",
]}

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
